[package]
name = "battery-notify"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
battery = "0.7"
notify-rust = "4"
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.5" }
