[package]
name = "battery-notify"
version = "0.3.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starship-battery = "0.8"
env_logger = "0.10"
log = "0.4"
notify-rust = "4.9"
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.7" }
